### ISSUE TITLE
Not working anymore on recent versions of Vim

### ISSUE THREAD

**Issue by adriaanzon** [adriaanzon/vim-textobj-matchit#1]
Does work on Neovim.

See https://circleci.com/gh/adriaanzon/vim-textobj-matchit/30

**Comment by adriaanzon** [comment]
Patterns with backreferences are passed to `match()` which is invalid.

**Comment by MahbubAlam231** [comment]
I have vim 8.2 and `vim-scripts/matchit.zip`, `textobj-matchit` isn't working. Maybe I couldn't set up properly. Would be glad if you could help.
